name: Build ISO

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install curl make -y
          curl https://nixos.org/nix/install | sh
      - name: Build ISO
        run: |
          sudo make build-iso
